version: '3'
services:
  api:
    build:
      context: ./
    ports:
      - "8080:80"
    volumes:
      - ./api/:/var/www/api/
    environment:
      MYSQL_CONTAINER_NAME: mysql
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/:/var/lib/mysql/